kind: workflow

nodes:

  docker1:
    type: docker
    image: busybox:latest
    image-pull-auth: docker

jobs:

  job1:
    steps:

    - name: s1
      node: docker1
      run: |
        echo Hello from Local
        ls
